@BaseURL = http://localhost:8088

### Lista as farmácias credenciadas de um bairro específico;
GET {{BaseURL}}/pharmacy?state=SP&city=SAO%20PAULO&neighb=BRAS

### Lista os tipos de medicamentos do Farmácia Popular;
GET {{BaseURL}}/medication

### Lista nome dos medicamentos com indicação para um sintoma (asma,diabetes...);
GET {{BaseURL}}/medication/1

### Lista as farmácias de um bairro que possuem o medicamento especifico;
GET {{BaseURL}}/medication/MED001/pharmacys?state=SP&city=SAO%20PAULO&neighb=BRAS
