@BaseURL = http://localhost:8088

### Lista as farmácias credenciadas de um bairro específico;
GET {{BaseURL}}/pharmacy?state=SP&city=SAO%20PAULO&neighb=BRAS

### Lista os tipos de medicamentos do Farmácia Popular;
GET {{BaseURL}}/medication

### Lista nome dos medicamentos com indicação para um sintoma (asma,diabetes...);
GET {{BaseURL}}/medication/1

### Lista as farmácias de um bairro que possuem o medicamento especifico;
GET {{BaseURL}}/medication/MED001/pharmacys?state=SP&city=SAO%20PAULO&neighb=BRAS

### Cadastra feedback de medicamento e farmacia consultadas pelo usuário;
POST {{BaseURL}}/feedback/medication
Content-Type: application/json

[
  {
    "medicineCode": "MED001",
    "medicineName": "brometo de ipratrópio 0,02mg",
    "quantity": 6,
    "stockStatus": "CRITICAL",
    "pharmacyUnit": {
      "name": "DROGA DARCIE LTDA. - EPP",
      "address": "AVENIDA CELSO GARCIA 406",
      "neighborhood": "BRAS",
      "city": "SAO PAULO",
      "state": "SP"
    }
  }
]

### Cadatra feedback de farmácias consultadas pelo usuário;
POST {{BaseURL}}/feedback/pharmacy
Content-Type: application/json

[
  {
    "name": "DROGA DARCIE LTDA. - EPP",
    "address": "AVENIDA CELSO GARCIA 406",
    "neighborhood": "BRAS",
    "city": "SAO PAULO",
    "state": "SP"
  },
  {
    "name": "DROGARIA FARMA LUISA LTDA - ME",
    "address": "AV. CELSO GARCIA, Nº 1907 - LOJA 08",
    "neighborhood": "BRAS",
    "city": "SAO PAULO",
    "state": "SP"
  },
  {
    "name": "DROGARIA SAO PAULO S.A.",
    "address": "AVENIDA RANGEL PESTANA, 2078",
    "neighborhood": "BRAS",
    "city": "SAO PAULO",
    "state": "SP"
  },
  {
    "name": "FARMACIA DE MANIPULACAO SINETE LTDA",
    "address": "RUA BRESSER",
    "neighborhood": "BRAS",
    "city": "SAO PAULO",
    "state": "SP"
  },
  {
    "name": "DROGARIA E PERFUMARIA BRESSER LTDA",
    "address": "RUA BRESSER Nº 1448",
    "neighborhood": "BRAS",
    "city": "SAO PAULO",
    "state": "SP"
  },
  {
    "name": "DROGASIL S.A.",
    "address": "AV. RANGEL PESTANA Nº 1996",
    "neighborhood": "BRAS",
    "city": "SAO PAULO",
    "state": "SP"
  }
]